#%RAML 1.0 DataType

type: object
properties:
      orderItemID:
        description: unique Id corresponds to orderItem
        example: 1
        type: number
        format: int
      orderID:
        description: unique Id corresponds to order
        example: 1
        type: number
        format: int
      itemID:
          description: unique Id corresponds to item
          example: 1
          type: number
          format: int
      itemCount:
          description: count of Items ordered
          example: 1
          type: number
          format: int